#!/bin/bash
# todo: loop over all *.txt files of a dir
./main "testfiles/tc0.txt" "testfiles/tc0.out.txt"  "testfiles/tc0.png"
./main "testfiles/tc1.txt" "testfiles/tc1.out.txt" "testfiles/tc1.png"
./main "testfiles/tc2.txt" "testfiles/tc2.out.txt" "testfiles/tc2.png"
./main "testfiles/tc3.txt" "testfiles/tc3.out.txt" "testfiles/tc3.png"
./main "testfiles/tc4.txt" "testfiles/tc4.out.txt" "testfiles/tc4.png"
./main "testfiles/tc5.txt" "testfiles/tc5.out.txt"  "testfiles/tc5.png"
./main "testfiles/tc6.txt" "testfiles/tc6.out.txt" "testfiles/tc6.png"
./main "testfiles/tc7.txt" "testfiles/tc7.out.txt" "testfiles/tc7.png"
./main "testfiles/tc7s.txt" "testfiles/tc7s.out.txt"  "testfiles/tc7s.png"
./main "testfiles/tc7ss.txt" "testfiles/tc7ss.out.txt" "testfiles/tc7ss.png"
./main "testfiles/tc8.txt" "testfiles/tc8.out.txt" "testfiles/tc8.png"
./main "testfiles/tc8s.txt" "testfiles/tc8s.out.txt" "testfiles/tc8s.png"
./main "testfiles/tc_cw2014.txt" "testfiles/tc_cw2014.out.txt"  "testfiles/tc_cw2014.png"
./main "testfiles/tc_hr00.txt" "testfiles/tc_hr00.out.txt" "testfiles/tc_hr00.png"
./main "testfiles/tc_hr01.txt" "testfiles/tc_hr01.out.txt" "testfiles/tc_hr01.png"
./main "testfiles/tc_reimai.txt" "testfiles/tc_reimai.out.txt" "testfiles/tc_reimai.png"
# and now the big one
./main "testfiles/hr_testcase4.txt" "testfiles/hr_testcase4.out.txt" "testfiles/hr_testcase4.png"
